SELECT distinct m.MITARBEITER_ID
FROM MITARBEITER m,
     FUNKTION f,
     ZUWEISUNG_MITARBEITER_FUNKTION z
WHERE f.FUNKTIONS_ID = z.FUNKTIONS_ID
  AND z.MITARBEITER_ID = m.MITARBEITER_ID AND f.BEZEICHNUNG='Kassierer*in' OR f.BEZEICHNUNG='Oberkassierer*in'